#!/usr/bin/env bash

# Change kitty, nvim, tmux, XMonad, Xmobar themes.
# This script supports hot reload except for nvim.
# $1 - theme
# Supported themes are
# latte
# macchiato
# nord
# onedark

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
source "$DIR/lib/helper.sh"

if [ -z "$1" ]; then
    echoerr "Missing argument"
    exit 1
fi

catpuccins=("latte" "frappe" "macchiato" "mocha")
config_dir="$HOME/.config"
theme="$1"

change_line() {
    grep -q "$2" "$3" && return
    sed -i "s|$1|$2|g" "$3" || echo "Cannot modify $3"
}

change_theme_kitty() {

    change_line "include ./themes/.*" "include ./themes/$theme.conf" "$config_dir"/kitty/kitty-all.conf

    # Send kitty the SIGUSR1 to reload the config file
    # https://sw.kovidgoyal.net/kitty/conf/
    kill -SIGUSR1 $(pgrep kitty)
}

change_theme_nvim() {

    nvim_theme="$theme"

    # e.g., latte -> catpuccin-latte
    [[ " ${catpuccins[@]} " =~ " ${theme} " ]] && nvim_theme="catppuccin-$theme"

    change_line "local colorscheme = .*" "local colorscheme = \"$nvim_theme\"" "$config_dir"/nvim/lua/user/colorscheme.lua
}

change_theme_xmobar() {

    if ! is_linux; then
        return 1
    fi

    xmobardir="$config_dir/xmobar"
    xmobarhs="$xmobardir/xmobar.hs"

    change_line "myTheme = .*Theme" "myTheme = ${theme}Theme" "$xmobarhs"

    # recompile Xmobar
    pushd "$xmobardir" || return 1
    stack ghc -- --make -o "$HOME/.local/bin/xmobar" "$xmobarhs"
    popd || return 1
}

change_theme_xmonad() {

    if ! is_linux; then
        return 1
    fi

    change_line "myTheme = .*Theme" "myTheme = ${theme}Theme" "$config_dir/xmonad/xmonad.hs"

    xmonad --restart
}

# Xmobar must be changed before XMonad
change_theme_xmobar
change_theme_xmonad

change_theme_kitty

change_theme_nvim

change_theme_tmux "$theme"
