#!/usr/bin/env bash

# Pull all git repos in $GIT_DIR whose git remote url matches $GIT_REMOTE.

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/helper.sh"

GIT_DIR="$HOME/git"

GIT_REMOTE="stjandra"

# Check if the git remote url matches the given name.
# $1 The name to match.
git_remote_match() {
    git config --get remote.origin.url | grep -q "$1"
}

cd "$GIT_DIR"

for repo in */ ; do

    cd "$GIT_DIR/$repo"

    if ! git_remote_match $GIT_REMOTE; then
        #output "Skipping $(pwd)"
        continue
    fi

    output "Pulling $(pwd)"
    git pull
    output ""

done
