#!/usr/bin/env bash

# A script that is executed once during macOS login.
# For more information how this script is executed:
# https://stackoverflow.com/a/13372744

# Run daemon from kitty in order to fix color issue
# when client is opened in terminal
#/usr/local/bin/alacritty -e /usr/local/bin/emacs --daemon=magit
/usr/local/bin/kitty --single-instance /usr/local/bin/emacs --daemon=magit

/usr/local/bin/emacs --daemon=main

ssh-add --apple-load-keychain
