#!/usr/bin/env bash

# A script that is executed once during macOS login.
# For more information how this script is executed:
# https://stackoverflow.com/a/13372744

start_emacs

ssh-add --apple-load-keychain
