#!/usr/bin/env bash

# Increase or decrease volume.
# $1 - The volume. Could be a relative percentage like -5% or +5%

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/pactl_helper.sh"

SINK=$(get_sink)


# Do nothing if sink is not set e.g., when no sound is playing
[ -z "$SINK" ] && exit 0

# https://wiki.archlinux.org/title/PulseAudio#Keyboard_volume_control
pactl set-sink-mute "$SINK" false
pactl set-sink-volume "$SINK" "$1"

notify_volume "$(get_volume)"
