#!/usr/bin/env bash

# Toggle mute and unmute.

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/pactl_helper.sh"

# https://wiki.archlinux.org/title/PulseAudio#Keyboard_volume_control
pactl set-sink-mute "$(get_sink)" toggle

if is_muted; then
    notify_volume "0"
else
    notify_volume "$(get_volume)"
fi
