#+TITLE: scripts-public

Some Bash scripts for convenience. Mostly used in my dotfiles or other scripts.

* amixer_toggle

Toggle sound (mute/unmute) with [[https://linux.die.net/man/1/amixer][amixer]].

* change_theme

Change the following theme:
- [[https://github.com/kovidgoyal/kitty][kitty]]
- [[https://github.com/neovim/neovim][nvim]]
- [[https://github.com/tmux/tmux][tmux]]

* change_theme_tmux

Change [[https://github.com/tmux/tmux][tmux]] theme.

* copy_fzf

Copy to clipboard strings that are regularly used with [[https://github.com/junegunn/fzf][fzf]].

* docker_macos

A script to open [[https://www.docker.com][Docker]] on macOS and block until Docker is initialized.

* git_clone

Loop through a set of git repos and clone them locally if missing.

* git_pull

Pull git repos belonging to a particular user.

* in_tmux

Whether we are in a [[https://github.com/tmux/tmux][tmux]] session.

* is_arch

Whether we are in an Arch Linux system.

* is_linux

Whether we are in a Linux system.

* is_macos

Whether we are in a macOS system.

* lf_ueberzug

Open the [[https://github.com/gokcehan/lf][lf]] file manager with [[https://github.com/jstkdng/ueberzugpp][Überzug++]] for image preview.

* mac_keystroke

Simulate hitting a key on OS X.

* mac_start

A script that is executed once during macOS login.
- Starts Emacs daemon.
- Add keys to the ssh agent with password from the keychain.

* my_battery

Prints the current battery status and capacity.

* my_date

Prints the current datetime in yyyy-mm-dd HH:MM format.

* my_light

Change screen brightness with [[https://github.com/haikarainen/light][light]].

* pactl_toggle

Toggle sound (mute/unmute) with [[https://linux.die.net/man/1/pactl][pactl]].

* pactl_volume

Change sound volume with [[https://linux.die.net/man/1/pactl][pactl]].

* start_emacs

Start [[https://www.gnu.org/software/emacs/][Emacs]] daemon.

* tmux_mycli

Run [[https://github.com/dbcli/mycli][mycli]] (a MySQL terminal client) and rename the current tmux window to host and database name.

* tmux_session

Create a new or switch to an existing tmux session with [[https://github.com/junegunn/fzf][fzf]].

* tmux_ssh

Ssh and rename the current [[https://github.com/tmux/tmux][tmux]] window to the ssh destination.

* url_decode

URL decode a string given via stdin or argument.

* url_encode

URL encode a string given via stdin or argument.

* vpn_ip

If connected to a vpn, get the ip.

* vpn_tb

Connect or disconnect [[https://tunnelblick.net][TunnelBlick]] VPN on macOS.
