#!/usr/bin/env bash

# Run ssh with the given arguments.
# If in tmux, rename the current tmux window to the given host.
# The host is assumed to be the last argument.
# $@ - ssh arguments.
#
# e.g. tmux_ssh user@host
#
# Note that complex command like the following does not work:
# tmux_ssh -t user@$host 'cd somedir; bash -l'
# Please see http://mywiki.wooledge.org/BashFAQ/050

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/helper.sh"
# shellcheck disable=SC1090
source "$DIR/lib/tmux_helper.sh"

# Use last argument as tmux window title.
run_cmd_tmux "${@: -1}" "ssh" "$@"
