#!/usr/bin/env bash

# Run ssh with the given arguments.
# If in tmux, rename the current tmux window to the given host.
# The host is assumed to be the last argument.
# $@ - ssh arguments.
#
# e.g. tmux_ssh user@host

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/helper.sh"
source "$DIR/lib/tmux_helper.sh"

# Try to get the hostname from the given arguments.
get_hostname() {

    # Normally a command is specified like:
    # tmux_ssh -t user@$host 'cd somedir; bash -l'

    # ${@: -1} - last argument.
    if echo "${@: -1}" | grep -qv "bash"; then
        # Last argument has no "bash", should be the hostname.
        echo "${@: -1}"
    else
        # Last argument has "bash", should be the 2nd to last argument.
        # ${@:(-2):1} - 2nd last argument.
        echo "${@:(-2):1}"
    fi
}

MY_HOST="$(get_hostname "$@")"

echo "host is $MY_HOST"

# Use last argument as tmux window title.
run_cmd_tmux "$MY_HOST" "ssh" "$@"
