#!/usr/bin/env bash

# Run ssh with the given arguments.
# If in tmux, rename the current tmux window to the given host.
# The host is assumed to be the last argument.
# $@ - ssh arguments.
#
# e.g. tmux_ssh user@host

set -euo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Source helper script.
# shellcheck disable=SC1090
source "$DIR/lib/helper.sh"
source "$DIR/lib/tmux_helper.sh"

# ${@: -1} - last argument.
# Use last argument as tmux window title.
run_cmd_tmux "${@: -1}" "ssh" "$@"
