#!/usr/bin/env bash

# Print the vpn ip if connected to a vpn.
# Otherwise print nothing.

get_ip() {
    sed -rn 's/.*inet\s([^ /]*).*/\1/p'
}

if command -v ifconfig &> /dev/null; then

    # Set interface
    if is_linux; then
        int="tun"
    elif is_macos; then
        int="utun"
    fi

    vpn_ip=$(ifconfig | grep -A1 "^$int" | tail -n1 | get_ip)

elif command -v ip &> /dev/null; then

    vpn_ip=$(ip addr | grep 'tun.$' | get_ip)

fi

[ -z "$vpn_ip" ] && exit 0

echo -n "vpn:$vpn_ip"
